# Eaternity API

This is the Eaternity API that can return the carbon impact of the food product/ ingrediant

In [12]:
import requests
import pandas as pd
from requests.auth import HTTPBasicAuth

YOUR_KEY = "SR012UWDjBT7fgivtbNZSp1IJylocm5a"
AUTH = HTTPBasicAuth(YOUR_KEY, "")
BASE_URL = "https://co2.eaternity.ch"

if YOUR_KEY == "CHANGEME":
    raise RuntimeError("Please change your api key!!")

def create_kitchen(name, kitchen_id, location):
    url = f"{BASE_URL}/api/kitchens/{kitchen_id}"

    body = {
        "kitchen": {
            "name": name,
            "location": location
        }
    }

    response = requests.put(url, json=body, auth=AUTH)
    if response.status_code not in [200, 201, 202]:
        print(f"ERROR: Failed PUTting kitchen {kitchen_id} with status {response.status_code}: '{response.text}'")
    else:
        print(f"SUCCESS: PUT kitchen {kitchen_id}")
        return response.json()

    
def put_recipe(recipe_id, kitchen_id, ingrediants):
    url = f"{BASE_URL}/api/kitchens/{kitchen_id}/recipes/{recipe_id}"

    for ingrediant in ingrediants:
        
    
        body = {
            "recipe": {
                "titles": [
                    {
                        "language": "en",
                        "value": "Carrots and onions"
                    }
                ],
                "date": "2020-09-19",
                "location": "Schweiz",
                "servings": 1,
                "ingredients": [
                    {
                        "id": "my_unique_carrot_id",
                        "names": [{"language": "en", "value": "Carrots"}],
                        "amount": 250,
                        "unit": "gram",
                        "origin": "Germany",
                        "transport": "ground",
                        "production": "standard",
                        "conservation": "fresh"
                    },
                    {
                        "id": "my_unique_onion_id",
                        "names": [{"language": "en", "value": "Onions"}],
                        "amount": 75,
                        "unit": "gram",
                        "origin": "Poland",
                        "transport": "ground",
                        "production": "standard",
                        "conservation": "dried"
                    }
                ]
            }
        }

    response = requests.put(url, json=body, auth=AUTH)
    if response.status_code not in [200, 201, 202]:
        print(f"ERROR: Failed PUTting recipe {recipe_id} with status {response.status_code}: '{response.text}'")
    else:
        print(f"SUCCESS: PUT recipe {recipe_id}")
        return response.json()


if __name__ == '__main__':
    kitchen_id = "my_first_kitchen"
    create_kitchen("My First Kitchen", kitchen_id, "Switzerland")
    
    xls = pd.ExcelFile('SwissRe Sourcing Data.xlsx')
    recipes = pd.read_excel(xls, 'Menus', header=1)
    #recipe_return = put_recipe("my_first_recipe", kitchen_id)
    print(recipe_return)

SUCCESS: PUT kitchen my_first_kitchen
{'statuscode': 200, 'message': '', 'request-id': 0, 'recipe-id': 'my_first_recipe', 'recipe': {'id': 'my_first_recipe', 'kitchen-id': 'my_first_kitchen', 'co2-value': 1460, 'eaternity-award': False, 'rating': 'C', 'titles': [{'language': 'en', 'value': 'Carrots and onions'}], 'date': '2020-09-19', 'location': 'Schweiz', 'servings': 1, 'recipe-portions': 1, 'ingredients': [], 'food-unit': 0.35705937121212117}}

In [13]:
recipes

,Menu + Option,Unnamed: 1,Name,Lactose free?,Gluten Free?,Vegan?,Vegetarian?,Grab and Go?,Amount g,Product 1,...,Amount g.8,Product 9,Amount g.9,Product 10,Amount g.10,Product 11,Amount g.11,Product 12,Amount g.12,Product 13
0,Menu 1,Option 1,Chantarelle Sour Cream,NaN,x,NaN,x,x,150.0,Chantarelle mushrooms,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Option 2,Roast Beef,NaN,x,NaN,NaN,NaN,210.0,Beef,...,40.0,Parmesan cheese,10.0,cream,50.0,Tomatoes,100.0,Zucchini,50.0,Red bell pepper
2,NaN,Option 3,Pasta,NaN,NaN,x,x,NaN,120.0,Spaghetti,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Option 4,Fish stikcs with vegetables,NaN,x,NaN,NaN,x,200.0,Fish sticks,...,10.0,garlic,20.0,canola oil,15.0,soy sauce,10.0,sambal,NaN,NaN
4,NaN,Option 5,Ham Sandich,NaN,NaN,NaN,NaN,x,200.0,bread,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,NaN,Option 2,Veal with chantarelles and fetuccine,NaN,NaN,NaN,NaN,NaN,180.0,veal,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,NaN,Option 3,Fillet of Sea-bass with rice,NaN,NaN,NaN,NaN,NaN,190.0,sea bass fish,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,NaN,Option 4,Cevapcici with ajvar,NaN,NaN,NaN,NaN,NaN,180.0,beef,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,NaN,Option 5,Fresh salad,NaN,NaN,NaN,NaN,NaN,80.0,red cabbage,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150,NaN,Option 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
vegetarian = recipes.loc[recipes['Vegetarian?'] == 'x']

In [15]:
vegetarian.head()

,Menu + Option,Unnamed: 1,Name,Lactose free?,Gluten Free?,Vegan?,Vegetarian?,Grab and Go?,Amount g,Product 1,...,Amount g.8,Product 9,Amount g.9,Product 10,Amount g.10,Product 11,Amount g.11,Product 12,Amount g.12,Product 13
0,Menu 1,Option 1,Chantarelle Sour Cream,NaN,x,NaN,x,x,150.0,Chantarelle mushrooms,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Option 3,Pasta,NaN,NaN,x,x,NaN,120.0,Spaghetti,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Option 6,Vegi Sandwich,NaN,NaN,x,x,x,200.0,bread,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Menu 2,Option 1,Tomato soup,NaN,x,x,x,x,150.0,tomatoes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Option 4,Shakshuka,x,x,NaN,x,NaN,200.0,tomatoes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
vegan = recipes.loc[recipes['Vegan?'] == 'x']

In [17]:
vegan.head()

,Menu + Option,Unnamed: 1,Name,Lactose free?,Gluten Free?,Vegan?,Vegetarian?,Grab and Go?,Amount g,Product 1,...,Amount g.8,Product 9,Amount g.9,Product 10,Amount g.10,Product 11,Amount g.11,Product 12,Amount g.12,Product 13
2,NaN,Option 3,Pasta,NaN,NaN,x,x,NaN,120.0,Spaghetti,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Option 6,Vegi Sandwich,NaN,NaN,x,x,x,200.0,bread,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Menu 2,Option 1,Tomato soup,NaN,x,x,x,x,150.0,tomatoes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Menu 4,Option 1,Lentil and coconut soup,x,x,x,x,x,40.0,red lentils,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Option 4,Peppers stuffed with tofu,x,x,x,x,x,150.0,Peppers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
meat = recipes.loc[recipes['Vegetarian?'] != 'x']

In [19]:
meat.head()

,Menu + Option,Unnamed: 1,Name,Lactose free?,Gluten Free?,Vegan?,Vegetarian?,Grab and Go?,Amount g,Product 1,...,Amount g.8,Product 9,Amount g.9,Product 10,Amount g.10,Product 11,Amount g.11,Product 12,Amount g.12,Product 13
1,NaN,Option 2,Roast Beef,NaN,x,NaN,NaN,NaN,210.0,Beef,...,40.0,Parmesan cheese,10.0,cream,50.0,Tomatoes,100.0,Zucchini,50.0,Red bell pepper
3,NaN,Option 4,Fish stikcs with vegetables,NaN,x,NaN,NaN,x,200.0,Fish sticks,...,10.0,garlic,20.0,canola oil,15.0,soy sauce,10.0,sambal,NaN,NaN
4,NaN,Option 5,Ham Sandich,NaN,NaN,NaN,NaN,x,200.0,bread,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Option 7,Chicken Satay Sandwich,NaN,NaN,NaN,NaN,x,200.0,bread,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Option 2,Sauteed Pork steam,NaN,NaN,NaN,NaN,NaN,210.0,Pork,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
recipes = {}
for index, row in recipes.iterrows():
    recipe = {}
    rowiter = 0
    for rowiter < 34:
        if row[rowiter] != None:
            recipe[row[rowiter+1]] = 
    recipes[row['name']] =